// Code generated by demobiggen; DO NOT EDIT.
package demobig

// This is the small default. Demo builds regenerate it larger.

var LookupStrings = []string{
	"demo-0001", "demo-0002", "demo-0003", "demo-0004", "demo-0005",
	"demo-0006", "demo-0007", "demo-0008", "demo-0009", "demo-0010",
}

var LookupInts = []int{
	1, 2, 3, 4, 5,
	6, 7, 8, 9, 10,
}

