import fs from "node:fs/promises";
import path from "node:path";

const out = path.resolve("src/generated/demobig.ts");
const n = Number.parseInt(process.env.DEMO_BIG_N ?? "2000", 10);
const count = Number.isFinite(n) && n > 0 ? n : 2000;

await fs.mkdir(path.dirname(out), { recursive: true });

let s = "";
s += "// Code generated by demobiggen; DO NOT EDIT.\n";
s += "export const DEMO_BIG_WORDS: string[] = [\n";
for (let i = 1; i <= count; i++) {
  const word = `word_${String(i).padStart(6, "0")}_${"x".repeat(64)}`;
  s += `  ${JSON.stringify(word)},\n`;
}
s += "];\n";
s += "\n";
s += "export function demoBigSum(): number {\n";
s += "  let x = 0;\n";
s += "  for (let i = 0; i < DEMO_BIG_WORDS.length; i++) x ^= DEMO_BIG_WORDS[i].length + i;\n";
s += "  return x;\n";
s += "}\n";

await fs.writeFile(out, s, "utf8");
console.log(`wrote ${out} (${count} entries)`);

