package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	outPath := flag.String("out", "internal/demobig/generated.go", "output file path (relative to backend/)")
	n := flag.Int("n", 0, "number of entries (overrides DEMO_BIG_N)")
	flag.Parse()

	count := *n
	if count <= 0 {
		if v := strings.TrimSpace(os.Getenv("DEMO_BIG_N")); v != "" {
			if x, err := strconv.Atoi(v); err == nil {
				count = x
			}
		}
	}
	if count <= 0 {
		count = 20000 // default big (enough to be noticeable)
	}

	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		fatalf("mkdir: %v", err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by demobiggen; DO NOT EDIT.\n")
	b.WriteString("package demobig\n\n")
	b.WriteString("// Generated size knob: DEMO_BIG_N\n\n")

	b.WriteString("var LookupStrings = []string{\n")
	for i := 1; i <= count; i++ {
		fmt.Fprintf(&b, "\t%q,\n", fmt.Sprintf("demo-%06d-%s", i, strings.Repeat("x", 32)))
	}
	b.WriteString("}\n\n")

	b.WriteString("var LookupInts = []int{\n")
	for i := 1; i <= count; i++ {
		fmt.Fprintf(&b, "\t%d,\n", i*i+i)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(*outPath, []byte(b.String()), 0o644); err != nil {
		fatalf("write: %v", err)
	}
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

